name: Lint

on:
    pull_request:
        branches:
            - main

jobs:
    lint:
        name: Lint check
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Use Bun
              uses: oven-sh/setup-bun@v2
              with:
                  bun-version: latest
            - run: bun install
            - run: bun lint
